name: Upload Python Package

# 配置工作流程触发的事件类型为发布版本（release），并且仅在发布版本被发布（published）时触发。
on:
  release:
    types: [published]

# 配置文件权限为读取（contents: read），表示工作流可以读取仓库中的文件内容。
permissions:
  contents: read

# 定义一个名为 deploy 的任务，表示用于部署 Python 包的任务。
jobs:
  deploy:
    # 配置任务在最新版本的 Ubuntu 系统上运行。
    runs-on: ubuntu-latest

    # 在任务中配置了一系列步骤：
    steps:
      # 使用 actions/checkout 动作来获取仓库代码。
      - uses: actions/checkout@v3

      # 使用 actions/setup-python 动作来设置 Python 环境，指定使用 Python 3.10 版本。
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # 安装 Poetry 和依赖包。
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.poetry/env
          poetry install

      # 使用 Poetry 构建 Python 包。
      - name: Build package
        run: poetry build

      # 上传 Python 包到 PyPI 仓库中。
      - name: Publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
